///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTestOne
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestOneRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("8c16c967-1454-4e14-ace4-79a7f1717312")]
    public partial class MyTestOneRepository : RepoGenBaseFolder
    {
        static MyTestOneRepository instance = new MyTestOneRepository();

        /// <summary>
        /// Gets the singleton class instance representing the MyTestOneRepository element repository.
        /// </summary>
        [RepositoryFolder("8c16c967-1454-4e14-ace4-79a7f1717312")]
        public static MyTestOneRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestOneRepository() 
            : base("MyTestOneRepository", "/", null, 0, false, "8c16c967-1454-4e14-ace4-79a7f1717312", ".\\RepositoryImages\\MyTestOneRepository8c16c967.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("8c16c967-1454-4e14-ace4-79a7f1717312")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class MyTestOneRepositoryFolders
    {
    }
#pragma warning restore 0436
}